# Generated by Django 4.2.1 on 2023-05-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_newpost_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newpost",
            name="created_at",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
