# Generated by Django 4.2.1 on 2023-05-29 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_newpost_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="newpost",
            name="dateCreated",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
