# Generated by Django 4.2.1 on 2023-05-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_newpost_datecreated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todolist",
            name="user",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="ToDoList",
        ),
    ]
