# Generated by Django 4.2.1 on 2023-05-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profilePic",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
